#!/bin/bash
# sudo apt update

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt install -y nodejs

sudo useradd --create-home webrunner
sudo usermod --shell /bin/bash webrunner
# sudo cp /home/ser/python_cre_sh/py_config /etc/systemd/system/pythonserve.service
sudo chmod -R 777 /home/webrunner

cd /home/webrunner

git clone -b dev https://github.com/yamileon/poolmanager-api.git

cd /home/webrunner/poolmanager-api
npm install 

echo '[Unit]
Description=api server

[Service]
User=webrunner

WorkingDirectory=/home/webrunner/poolmanager-api

ExecStart=/usr/bin/node index.js

[Install]

WantedBy=multi-user.target' | sudo tee /etc/systemd/system/poolmanagerapi.service

echo "exports.app = {
    PORT: 8080,
    MONGODB_URI: 'mongodb://"$1":27017/qac',
    logErrors: true
};" > /home/webrunner/poolmanager-api/config.js


sudo systemctl start poolmanagerapi

sudo systemctl enable poolmanagerapi