#!/bin/bash
sudo apt update

sudo mkdir -p /data/db

sudo apt install -y mongodb



sleep 10 && sudo systemctl stop mongodb.service

sudo rm /lib/systemd/system/mongodb.service

cp ./mongodb.conf /lib/systemd/system/mongodb.service

sudo systemctl start mongodb.service

# sudo systemctl start mongodb