#!/bin/bash
sudo apt update

sudo mkdir -p /data/db

sudo apt install -y mongodb



sleep 10 && sudo systemctl stop mongodb.service

# sudo mongod --bind_ip_all

sudo rm /lib/systemd/system/mongodb.service

sudo cp .mongodb.service /lib/systemd/system/mongodb.service

sudo systemctl daemon-reload

sudo systemctl start mongodb.service

# sudo systemctl start mongodb